# Generated by Django 4.2.4 on 2023-08-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="PostOffice",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="places.place",
                    ),
                ),
                ("accepts_parcels", models.BooleanField(default=False)),
                ("has_atm", models.BooleanField(default=False)),
            ],
            bases=("places.place",),
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "place_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="places.place",
                    ),
                ),
                ("serves_hot_dogs", models.BooleanField(default=False)),
                ("serves_pizza", models.BooleanField(default=False)),
            ],
            bases=("places.place",),
        ),
    ]
