# Generated by Django 4.2.4 on 2023-08-24 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_create_entries"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostOffice",
        ),
    ]
